version: '3'

services:
  ipfs:
    image: jbenet/go-ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]
  postgres:
    image: postgres:9.6.5-alpine
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  identifi:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: api
    ports:
      - "4944:4944" # identifi-daemon
      - "8000:8000" # identifi-angular
    user: node
    volumes:
      - ./identifi-daemon:/identifi-daemon
      - ./identifi-angular:/identifi-angular
    working_dir: /identifi-daemon
    command: ["/usr/src/app/wait-for", "ipfs:5001", "--", "npm", "start"]
    depends_on:
      - postgres
      - ipfs

volumes:
  db:
