version: '3'

services:
  ipfs:
    image: jbenet/go-ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
  identifi-db:
    image: postgres:9.6.5-alpine
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  identifi-src:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: api
    ports:
      - "4944:4944" # identifi-daemon
      - "8000:8000" # identifi-angular
    user: node
    working_dir: /usr/src/app
    command: ["./wait-for", "ipfs:4001", "--", "node", "identifi-daemon/server.js"]
    depends_on:
      - identifi-db
      - ipfs

volumes:
  db:
