version: '3'

services:
  ipfs:
    image: jbenet/go-ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]
  postgres:
    image: postgres:9.6.5-alpine
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  identifi-angular:
    build:
      context: ./
      dockerfile: Dockerfile-angular
    ports:
      - "3000:3000" # identifi-angular
    user: node
    volumes:
      - ./identifi-angular:/identifi-angular
    working_dir: /identifi-angular
    command:
      - /bin/sh
      - -c
      - |
          cp -r /usr/src/app/identifi-angular/node_modules /identifi-angular
          gulp serve
    depends_on:
      - identifi-daemon
  identifi-daemon:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4944:4944" # identifi-daemon
    user: node
    volumes:
      - ./identifi-daemon:/identifi-daemon
    working_dir: /identifi-daemon
    command:
      - /bin/sh
      - -c
      - |
          cp -r /usr/src/app/identifi-daemon/node_modules /identifi-daemon
          /usr/src/app/wait-for ipfs:5001 -- npm start
    depends_on:
      - postgres
      - ipfs

volumes:
  db:
